# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPtHwmu42c-RhLbqg4m9utPGGdQCj9CT
"""

import streamlit as st
import joblib

# Load model + vectorizer
model = joblib.load("phishing_model.pkl")
tfidf = joblib.load("tfidf.pkl")

st.title("📧 Phishing Email Detector")
st.write("Paste an email and check if it's phishing or legit.")

email = st.text_area("Email content")

if st.button("Predict"):
    if email.strip() == "":
        st.warning("Please enter an email.")
    else:
        # transform text
        X = tfidf.transform([email])

        # prediction
        pred = model.predict(X)[0]
        proba = model.predict_proba(X)[0][1]

        if pred == 1:
            st.error("🚨 PHISHING EMAIL")
        else:
            st.success("✅ LEGIT EMAIL")

        st.write(f"Confidence (phishing): {proba:.2f}")